# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_moneybook_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('EUR', 'Euros'), ('USD', 'Dollars')], max_length=3),
        ),
    ]
