# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170419_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('EUR', 'Euros'), ('USD', 'Dollars')], editable=False, max_length=3, primary_key=True, serialize=False),
        ),
    ]
