# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170419_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneybook',
            old_name='current_balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='moneybook',
            old_name='current_balance_currency',
            new_name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='moneybook',
            name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='moneybook',
            name='initial_balance_currency',
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('EUR', 'Euros'), ('USD', 'Dollars')], max_length=3, primary_key=True, serialize=False),
        ),
    ]
